# Generated by Django 5.2.5 on 2025-08-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="email",
            field=models.EmailField(max_length=255),
        ),
    ]
